remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: [Personal Projects]
description: [This repository houses a compilation of personal projects that I have accomplished during my CS Masters program and leisure time.]
